#!/bin/sh

VOSK_MODEL_PATH="$HOME/.local/share/vibey/vosk-model-small-en-us-0.15/"
INVIDIOUS_INSTANCE="https://vid.puffyan.us" 

mpc stop
mpc clear

ffmpeg -y -f alsa -i default -acodec pcm_s16le -ac 1 -ar 44100 -t 4 -f wav ~/.cache/audio.wav

vosk-transcriber -m $VOSK_MODEL_PATH -i ~/.cache/audio.wav -o ~/.cache/audio_text.txt
read audio_input < ~/.cache/audio_text.txt

google_speech " All right.. let me play.. $audio_input" &

query="$(printf '%s' "song audio $audio_input" | tr ' ' '+' )"

video_id="$(curl -s "$INVIDIOUS_INSTANCE/search?q=$query" | grep -Eo "watch\?v=.{11}" | head -n 1)"
youtube_url="https://youtube.com/$video_id"

audio_url="$(yt-dlp -f bestaudio --get-url "$youtube_url")"

mpc add "$audio_url"
mpc play

title=$(yt-dlp --get-title "$youtube_url")
notify-send "Playing: " "$title"
